// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Software_Requirement_Specification.Data;

namespace Software_Requirement_Specification.Migrations
{
    [DbContext(typeof(Software_Requirement_SpecificationContext))]
    [Migration("20220501203714_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Software_Requirement_Specification.Models.BaiGiang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KichThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiChinhSua")
                        .HasColumnType("int");

                    b.Property<int>("NguoiChinhSuaCuoi")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<bool>("PheDuyet")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("BaiGiang");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.BoMon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenBoMon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoMon");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.DeThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiPheDuyet")
                        .HasColumnType("int");

                    b.Property<bool>("PheDuyet")
                        .HasColumnType("bit");

                    b.Property<int>("TepId")
                        .HasColumnType("int");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TinhTrang")
                        .HasColumnType("bit");

                    b.Property<int>("idLopHoc")
                        .HasColumnType("int");

                    b.Property<int>("idMonHoc")
                        .HasColumnType("int");

                    b.Property<int?>("lopHocId")
                        .HasColumnType("int");

                    b.Property<int?>("monHocIdId")
                        .HasColumnType("int");

                    b.Property<string>("tendethi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("TepId")
                        .IsUnique();

                    b.HasIndex("lopHocId");

                    b.HasIndex("monHocIdId");

                    b.ToTable("DeThi");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.LoaiLopHoc", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("LoaiLopHoc");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.LopHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NienKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("loaiId")
                        .HasColumnType("int");

                    b.Property<int?>("loaiLopHocid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("loaiLopHocid");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoMonId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TinhTrang")
                        .HasColumnType("bit");

                    b.Property<int>("idLopHoc")
                        .HasColumnType("int");

                    b.Property<int?>("lopHocIdId")
                        .HasColumnType("int");

                    b.Property<int>("nguoiDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoMonId");

                    b.HasIndex("lopHocIdId");

                    b.HasIndex("nguoiDungId");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdtaiKhoan")
                        .HasColumnType("int");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VaitroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("VaitroId");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenQuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhanQuyen");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuyenIDId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("idQuyen")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuyenIDId");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("NgayGuiPheDuyet")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PheDuyet")
                        .HasColumnType("bit");

                    b.Property<bool>("TinhTrang")
                        .HasColumnType("bit");

                    b.Property<int>("idNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("monhocId")
                        .HasColumnType("int");

                    b.Property<int?>("nguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("tentailieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("monhocId");

                    b.HasIndex("nguoiDungId");

                    b.ToTable("TaiLieu");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.Tep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KichThuoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySuaCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiChinhSua")
                        .HasColumnType("int");

                    b.Property<int?>("TaiLieuId")
                        .HasColumnType("int");

                    b.Property<string>("TenTep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idTaiLieu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaiLieuId");

                    b.ToTable("Tep");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiLopHocId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiThongBao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LopHocId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoaiLopHocId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.ThuVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChiTruyCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HieuTruong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTruongHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgonNguXacDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NienKhoaMacDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHeThong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTruongHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThuVien");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("TenVaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongBao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idQuyen")
                        .HasColumnType("int");

                    b.Property<int?>("phanQuyenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("phanQuyenId");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.BaiGiang", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Requirement_Specification.Models.NguoiDung", "NguoiDung")
                        .WithMany("BaiGiang")
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.DeThi", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.NguoiDung", "NguoiDung")
                        .WithMany("DeThi")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Requirement_Specification.Models.Tep", "Tep")
                        .WithOne("DeThi")
                        .HasForeignKey("Software_Requirement_Specification.Models.DeThi", "TepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Requirement_Specification.Models.LopHoc", "lopHoc")
                        .WithMany("deThis")
                        .HasForeignKey("lopHocId");

                    b.HasOne("Software_Requirement_Specification.Models.MonHoc", "monHocId")
                        .WithMany("deThis")
                        .HasForeignKey("monHocIdId");

                    b.Navigation("lopHoc");

                    b.Navigation("monHocId");

                    b.Navigation("NguoiDung");

                    b.Navigation("Tep");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.LopHoc", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.LoaiLopHoc", "loaiLopHoc")
                        .WithMany()
                        .HasForeignKey("loaiLopHocid");

                    b.Navigation("loaiLopHoc");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.MonHoc", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.BoMon", "boMon")
                        .WithMany("monHocs")
                        .HasForeignKey("BoMonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Requirement_Specification.Models.LopHoc", "lopHocId")
                        .WithMany("monHocs")
                        .HasForeignKey("lopHocIdId");

                    b.HasOne("Software_Requirement_Specification.Models.NguoiDung", "nguoiDung")
                        .WithMany()
                        .HasForeignKey("nguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("boMon");

                    b.Navigation("lopHocId");

                    b.Navigation("nguoiDung");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.NguoiDung", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Requirement_Specification.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId");

                    b.HasOne("Software_Requirement_Specification.Models.VaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("VaitroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("TaiKhoan");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiKhoan", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.PhanQuyen", "QuyenID")
                        .WithMany()
                        .HasForeignKey("QuyenIDId");

                    b.Navigation("QuyenID");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiLieu", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.MonHoc", "monHoc")
                        .WithMany("taiLieus")
                        .HasForeignKey("monhocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Requirement_Specification.Models.NguoiDung", "nguoiDung")
                        .WithMany("TaiLieu")
                        .HasForeignKey("nguoiDungId");

                    b.Navigation("monHoc");

                    b.Navigation("nguoiDung");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.Tep", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.TaiLieu", "TaiLieu")
                        .WithMany("tep")
                        .HasForeignKey("TaiLieuId");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.ThongBao", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.LoaiLopHoc", "loaiLopHoc")
                        .WithMany("thongBaos")
                        .HasForeignKey("LoaiLopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Requirement_Specification.Models.LopHoc", null)
                        .WithMany("thongBaos")
                        .HasForeignKey("LopHocId");

                    b.HasOne("Software_Requirement_Specification.Models.NguoiDung", "nguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("loaiLopHoc");

                    b.Navigation("nguoiDung");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.VaiTro", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.TaiKhoan", null)
                        .WithMany("vaiTro")
                        .HasForeignKey("TaiKhoanId");

                    b.HasOne("Software_Requirement_Specification.Models.PhanQuyen", "phanQuyen")
                        .WithMany()
                        .HasForeignKey("phanQuyenId");

                    b.Navigation("phanQuyen");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.BoMon", b =>
                {
                    b.Navigation("monHocs");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.LoaiLopHoc", b =>
                {
                    b.Navigation("thongBaos");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.LopHoc", b =>
                {
                    b.Navigation("deThis");

                    b.Navigation("monHocs");

                    b.Navigation("thongBaos");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.MonHoc", b =>
                {
                    b.Navigation("deThis");

                    b.Navigation("taiLieus");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiGiang");

                    b.Navigation("DeThi");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiKhoan", b =>
                {
                    b.Navigation("vaiTro");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiLieu", b =>
                {
                    b.Navigation("tep");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.Tep", b =>
                {
                    b.Navigation("DeThi");
                });
#pragma warning restore 612, 618
        }
    }
}
