// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Software_Requirement_Specification.Data;

namespace Software_Requirement_Specification.Migrations
{
    [DbContext(typeof(Software_Requirement_SpecificationContext))]
    [Migration("20220420044721_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Software_Requirement_Specification.Models.BaiGiang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KichThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiChinhSua")
                        .HasColumnType("int");

                    b.Property<int>("NguoiChinhSuaCuoi")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<bool>("PheDuyet")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("BaiGiang");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.DeThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiPheDuyet")
                        .HasColumnType("int");

                    b.Property<bool>("PheDuyet")
                        .HasColumnType("bit");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TinhTrang")
                        .HasColumnType("bit");

                    b.Property<int>("idMonHoc")
                        .HasColumnType("int");

                    b.Property<int?>("monHocIdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("monHocIdId");

                    b.ToTable("DeThi");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.LopHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NienKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TruongIDId")
                        .HasColumnType("int");

                    b.Property<int>("idtruong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TruongIDId");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TinhTrang")
                        .HasColumnType("bit");

                    b.Property<int>("idLopHoc")
                        .HasColumnType("int");

                    b.Property<int?>("lopHocIdId")
                        .HasColumnType("int");

                    b.Property<string>("maNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("vaiTroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("lopHocIdId");

                    b.HasIndex("vaiTroId");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VaitroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("VaitroId");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenQuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhanQuyen");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuyenIDId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("idQuyen")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuyenIDId");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MonHocIDId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGuiPheDuyet")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("SoTaiLieuChoDuyet")
                        .HasColumnType("int");

                    b.Property<string>("TenMonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TinhTrang")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MonHocIDId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("TaiLieu");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.Tep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BaiGiangId")
                        .HasColumnType("int");

                    b.Property<int?>("DeThiId")
                        .HasColumnType("int");

                    b.Property<int>("KichThuoc")
                        .HasColumnType("int");

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaiLieuId")
                        .HasColumnType("int");

                    b.Property<string>("TenFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiGiangId");

                    b.HasIndex("DeThiId");

                    b.HasIndex("TaiLieuId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("Tep");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.ThuVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChiTruyCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgonNguXacDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NienKhoaMacDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHeThong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("TruongHocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TruongHocId")
                        .IsUnique();

                    b.ToTable("ThuVien");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TruongHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HieuTruong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTruong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idThuVien")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TruongHoc");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("TenVaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongBao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idQuyen")
                        .HasColumnType("int");

                    b.Property<int?>("phanQuyenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("phanQuyenId");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.BaiGiang", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Requirement_Specification.Models.NguoiDung", "NguoiDung")
                        .WithMany("BaiGiang")
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.DeThi", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.NguoiDung", "NguoiDung")
                        .WithMany("DeThi")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Requirement_Specification.Models.MonHoc", "monHocId")
                        .WithMany("deThis")
                        .HasForeignKey("monHocIdId");

                    b.Navigation("monHocId");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.LopHoc", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.TruongHoc", "TruongID")
                        .WithMany("lopHocs")
                        .HasForeignKey("TruongIDId");

                    b.Navigation("TruongID");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.MonHoc", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.LopHoc", "lopHocId")
                        .WithMany("monHocs")
                        .HasForeignKey("lopHocIdId");

                    b.HasOne("Software_Requirement_Specification.Models.VaiTro", "vaiTro")
                        .WithMany()
                        .HasForeignKey("vaiTroId");

                    b.Navigation("lopHocId");

                    b.Navigation("vaiTro");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.NguoiDung", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Requirement_Specification.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId");

                    b.HasOne("Software_Requirement_Specification.Models.VaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("VaitroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("TaiKhoan");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiKhoan", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.PhanQuyen", "QuyenID")
                        .WithMany()
                        .HasForeignKey("QuyenIDId");

                    b.Navigation("QuyenID");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiLieu", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.MonHoc", "MonHocID")
                        .WithMany("taiLieus")
                        .HasForeignKey("MonHocIDId");

                    b.HasOne("Software_Requirement_Specification.Models.NguoiDung", null)
                        .WithMany("TaiLieu")
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("MonHocID");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.Tep", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.BaiGiang", "BaiGiang")
                        .WithMany()
                        .HasForeignKey("BaiGiangId");

                    b.HasOne("Software_Requirement_Specification.Models.DeThi", "DeThi")
                        .WithMany("teps")
                        .HasForeignKey("DeThiId");

                    b.HasOne("Software_Requirement_Specification.Models.TaiLieu", "TaiLieu")
                        .WithMany("tep")
                        .HasForeignKey("TaiLieuId");

                    b.HasOne("Software_Requirement_Specification.Models.VaiTro", "VaiTro")
                        .WithMany("tep")
                        .HasForeignKey("VaiTroId");

                    b.Navigation("BaiGiang");

                    b.Navigation("DeThi");

                    b.Navigation("TaiLieu");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.ThuVien", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.TruongHoc", "TruongHoc")
                        .WithOne("thuVien")
                        .HasForeignKey("Software_Requirement_Specification.Models.ThuVien", "TruongHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TruongHoc");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.VaiTro", b =>
                {
                    b.HasOne("Software_Requirement_Specification.Models.TaiKhoan", null)
                        .WithMany("vaiTro")
                        .HasForeignKey("TaiKhoanId");

                    b.HasOne("Software_Requirement_Specification.Models.PhanQuyen", "phanQuyen")
                        .WithMany()
                        .HasForeignKey("phanQuyenId");

                    b.Navigation("phanQuyen");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.DeThi", b =>
                {
                    b.Navigation("teps");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.LopHoc", b =>
                {
                    b.Navigation("monHocs");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.MonHoc", b =>
                {
                    b.Navigation("deThis");

                    b.Navigation("taiLieus");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiGiang");

                    b.Navigation("DeThi");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiKhoan", b =>
                {
                    b.Navigation("vaiTro");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TaiLieu", b =>
                {
                    b.Navigation("tep");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.TruongHoc", b =>
                {
                    b.Navigation("lopHocs");

                    b.Navigation("thuVien");
                });

            modelBuilder.Entity("Software_Requirement_Specification.Models.VaiTro", b =>
                {
                    b.Navigation("tep");
                });
#pragma warning restore 612, 618
        }
    }
}
